Crewd.WebSite/Controllers/CourseApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Crewd.Persistence;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Crewd.WebSite.Controllers
{
    public class CourseApplicationsController : Controller
    {
        private static HttpClient client;
        private static readonly string baseAdress = "http://api:5000/";

        public CourseApplicationsController()
        {
            client = new HttpClient()
            {
                BaseAddress = new Uri(baseAdress)
            };
        }

        // Get the Skills belonging to the selected course and redirect to course application page
        public async Task<IActionResult> Join(String CourseId)
        {

            byte[] token;
            if (!HttpContext.Session.TryGetValue("auth_token", out token))
            {
                return RedirectToAction("List", "Courses");
            }
            String Auth = Encoding.ASCII.GetString(token);

            HttpResponseMessage Response = await client.GetAsync("api/applications/skills/" + CourseId + "/" + Auth);

            if (Response.IsSuccessStatusCode)
            {
                IEnumerable<Skill> Skills = JsonConvert.DeserializeObject<IEnumerable<Skill>>(await Response.Content.ReadAsStringAsync());

                JoinViewModel VM = new JoinViewModel(Skills.ToList(), CourseId);
                ViewBag.IsTeacher = await Utils.Helpers.UserHasRole(client, HttpContext, "teacher");
                ViewBag.IsUniversity = await Utils.Helpers.UserHasRole(client, HttpContext, "university");
                return View(VM);
            }

            String ErrorMessage = await Response.Content.ReadAsStringAsync(); 
            Console.WriteLine("Error while getting join page: " + ErrorMessage);
            TempData["ErrorMess"] = ErrorMessage;
            return RedirectToAction("List", "Courses");
        }

        // Post the course application and quiz answers to the API
        [HttpPost]
        public async Task<IActionResult> SubmitApplication(JoinViewModel VM)
        {           
            Console.WriteLine("course :" + VM.CourseId);

            byte[] token;
            if (!HttpContext.Session.TryGetValue("auth_token", out token))
            {
                return RedirectToAction("List", "Courses");
            }
            VM.Auth = Encoding.ASCII.GetString(token);

            var Response = await client.PostAsJsonAsync("api/applications/", VM);

            return RedirectToAction("List", "Courses");
        }

        // Return the student application approval page (For teachers only!)
        public async Task<IActionResult> AddStudent()
        {
            byte[] token;
            if (!HttpContext.Session.TryGetValue("auth_token", out token))
            {
                return RedirectToAction("List", "Courses");
            }
            String Auth = Encoding.ASCII.GetString(token);

            HttpResponseMessage Response = await client.GetAsync("api/applications/" + Auth);

            if (Response.IsSuccessStatusCode)
            {
                IEnumerable<CourseUser> Applications = JsonConvert.DeserializeObject<IEnumerable<CourseUser>>(await Response.Content.ReadAsStringAsync());
                ViewBag.IsTeacher = await Utils.Helpers.UserHasRole(client, HttpContext, "teacher");
                ViewBag.IsUniversity = await Utils.Helpers.UserHasRole(client, HttpContext, "university");
                return View(Applications.ToList());
            }

            Console.WriteLine("error getting applications :" + Response.StatusCode);
            return RedirectToAction("List", "Courses");
        }

        // Reject course application, delete it from the db
        public async Task<IActionResult> RejectApplication(String Id)
        {
            HttpResponseMessage Response = await client.PutAsJsonAsync("api/applications/reject/" + Id, 0);

            return RedirectToAction("AddStudent");
        }

        // Approve course application, update entry in db
        public async Task<IActionResult> ApproveApplication(String Id)
        {
            HttpResponseMessage Response = await client.PutAsJsonAsync("api/applications/approve/" + Id, 0);

            return RedirectToAction("AddStudent");
        }
    }
}

Crewd.WebSite/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Crewd.WebSite.Models;
using Crewd.Persistence;
using System.Net.Http;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http.Headers;
using System.Text;
using System.Net;

namespace Crewd.WebSite.Controllers
{
    public class CoursesController : Controller
    {
        private static HttpClient client;
        private static readonly string baseAdress = "http://api:5000/";

        public CoursesController()
        {
          
            HttpClientHandler clientHandler = new HttpClientHandler();
            clientHandler.UseCookies = true;
            //clientHandler.CookieContainer = new CookieContainer();
            clientHandler.UseDefaultCredentials = true;

            client = new HttpClient(clientHandler);
            client.BaseAddress = new Uri(baseAdress);
            MediaTypeWithQualityHeaderValue contentType = new MediaTypeWithQualityHeaderValue("text/plain");
            client.DefaultRequestHeaders.Accept.Add(contentType);
        }

        // Return the Add Course page (For teachers only!)
        public async Task<IActionResult> Add()
        {
            byte[] token;
            if (!HttpContext.Session.TryGetValue("auth_token", out token))
            {
                return RedirectToAction("List");
            }
            String Auth = Encoding.ASCII.GetString(token);

            HttpResponseMessage Response = await client.GetAsync("api/usertype/" + Auth);

            if(Response.IsSuccessStatusCode)
            {
                String Type = await Response.Content.ReadAsStringAsync();

                if(Type.Equals("teacher"))
                {
                    CourseViewModel VM = new CourseViewModel();
                    ViewBag.IsTeacher = await Utils.Helpers.UserHasRole(client, HttpContext, "teacher");
                    ViewBag.IsUniversity = await Utils.Helpers.UserHasRole(client, HttpContext, "university");
                    return View(VM);
                }
            }
           
            return RedirectToAction("List");
        }

        // Return new partial view with new question row to ajax call
        [HttpGet]
        public IActionResult AddQuestion()
        {
            var Skill = new SkillViewModel();       
            return PartialView("AddSkill", Skill);
        }

        // Add new Course (For teachers only!)
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(CourseViewModel Course)
        {
            if(ModelState.IsValid)
            {
                byte[] token;
                if (!HttpContext.Session.TryGetValue("auth_token", out token))
                {
                    return RedirectToAction("List");
                }
                Course.Auth = Encoding.ASCII.GetString(token);

                Console.WriteLine("posting course, nr of skills: " + Course.Skills.Count());
                Console.WriteLine(Course.Skills[0].Name);
                var Response = await client.PostAsJsonAsync("api/courses/", Course);

                if (Response.IsSuccessStatusCode)
                {
                    return RedirectToAction("List");
                }

            }

            return RedirectToAction("List");
        }

        // Return the page with the list of all courses
        public async Task<IActionResult> List()
        {
            byte[] token;
            if (!HttpContext.Session.TryGetValue("auth_token", out token))
            {
                return RedirectToAction("List");
            }
            String Auth = Encoding.ASCII.GetString(token);

            HttpResponseMessage Response = await client.GetAsync("api/courses/" + Auth);
            ViewBag.IsTeacher = await Utils.Helpers.UserHasRole(client, HttpContext, "teacher");
            ViewBag.IsUniversity = await Utils.Helpers.UserHasRole(client, HttpContext, "university");

            if (Response.IsSuccessStatusCode)
            {
                IEnumerable<Course> Courses = JsonConvert.DeserializeObject<IEnumerable<Course>>(await Response.Content.ReadAsStringAsync());
                return View(Courses.ToList());
            }
        
            Console.WriteLine("error getting courses :" + Response.StatusCode); 
            return View();
        }
        
        // Get the details of the course
        public async Task<IActionResult> Details(String CourseId)
        {
            byte[] token;
            if (!HttpContext.Session.TryGetValue("auth_token", out token))
            {
                return RedirectToAction("List");
            }
            String Auth = Encoding.ASCII.GetString(token);

            HttpResponseMessage Response = await client.GetAsync("api/courses/details/" + CourseId + "/" + Auth);

            if(Response.IsSuccessStatusCode)
            {
                DetailsViewModel Details = JsonConvert.DeserializeObject<DetailsViewModel>(await Response.Content.ReadAsStringAsync());
                ViewBag.IsTeacher = await Utils.Helpers.UserHasRole(client, HttpContext, "teacher");
                ViewBag.IsUniversity = await Utils.Helpers.UserHasRole(client, HttpContext, "university");
                return View("Details", Details);
            }

            return RedirectToAction("List");
        }

           

        // Close course registration (only permitted for the teacher who created the course)
        public async Task<IActionResult> Close(String CourseId)
        {
            byte[] token;
            if (!HttpContext.Session.TryGetValue("auth_token", out token))
            {
                return RedirectToAction("List");
            }
            String Auth = Encoding.ASCII.GetString(token);

            HttpResponseMessage Response = await client.PutAsync("api/courses/close/" + CourseId + "/" + Auth, null);

            if (!Response.IsSuccessStatusCode)
            {
                String ErrorMessage = await Response.Content.ReadAsStringAsync();

                Console.WriteLine("Error while closing this course " + ErrorMessage);              
                TempData["ErrorMess"] = ErrorMessage;
                return RedirectToAction("List");
            }

            Console.WriteLine("Course closed");
            TempData["SuccMess"] = "Course was closed successfully!";
            return RedirectToAction("List");
        }

        // Remove course (only permitted for the teacher who created the course)
        public async Task<IActionResult> Remove(String CourseId)
        {
            byte[] token;
            if (!HttpContext.Session.TryGetValue("auth_token", out token))
            {
                return RedirectToAction("List");
            }
            String Auth = Encoding.ASCII.GetString(token);

            HttpResponseMessage Response = await client.DeleteAsync("api/courses/" + CourseId + "/" + Auth);

            if(!Response.IsSuccessStatusCode)
            {
                String ErrorMessage = await Response.Content.ReadAsStringAsync();

                Console.WriteLine("Error deleting course " + ErrorMessage);
                TempData["ErrorMess"] = ErrorMessage;
                return RedirectToAction("List");
            }

            Console.WriteLine("Course removed");
            TempData["SuccMess"] = "Course was removed successfully!";
            return RedirectToAction("List");
        }

     

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Crewd.WebSite/Controllers/UniversityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Crewd.Persistence;
using System.Net.Http;
using System.Text;
using System.Net;

namespace Crewd.WebSite.Controllers
{
    public class UniversityController : Controller
    {
        private static HttpClient client;
        private static readonly string baseAdress = "http://api:5000/";

        public UniversityController()
        { 
             client = new HttpClient()
             {
                BaseAddress = new Uri(baseAdress)
             };
        }

        public IActionResult Index()
        {
            return View("AddTeachers");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(AddTeacherViewModel TeacherData)
        {
            if (ModelState.IsValid)
            {
                //Console.WriteLine("username: "+user.UserName);
                byte[] token;
                if (!HttpContext.Session.TryGetValue("auth_token", out token))
                {
                    return RedirectToAction("Login", "Login");
                }
                TeacherData.Auth = Encoding.ASCII.GetString(token);
  
                var response = await client.PostAsJsonAsync("api/university/", TeacherData);

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Login", "Login");
                }

            }

            return View("AddTeachers");
        }
    }
}

Crewd.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crewd</title>

    <!--
     <environment include="Development">
          <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
          <link rel="stylesheet" href="~/css/site.css" />
      </environment>
      <environment exclude="Development">
          <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
          <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
      </environment>-->

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/global.css">

</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a href="#" class="navbar-brand">
            <img src="~/images/crewd_logo_navbar.png" height="30" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupport">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                @if ((Boolean)(ViewData["IsTeacher"]))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Courses" asp-action="Add">Add Course</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="CourseApplications" asp-action="AddStudent">Manage Applications</a>
                    </li>
                }
                @if((Boolean)(ViewData["IsUniversity"]))
                {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="University" asp-action="Index">Teacher Administration</a>
                    </li>
                }
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Courses" asp-action="List">View Courses</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                </li>
            </ul>           
        </div>
    </nav>
   

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Crewd</p>
        </footer>
    </div>

    <!--
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
        -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="~/js/bootstrap.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>